services:
  - type: web
    runtime: docker
    name: fastapi-backend
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8000"
      - key: PYTHONUNBUFFERED
        value: "1"
    dockerfilePath: "app/backend/Dockerfile"

  - type: web
    name: streamlit-frontend
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8501"
      - key: PYTHONUNBUFFERED
        value: "1"
      # Setting the backend URL using Render's internal hostname convention
      - key: BACKEND_URL
        value: "http://fastapi-backend:8000"  # Connects Streamlit to FastAPI internally
    dockerfilePath: "app/frontend/Dockerfile"
